name: tutorial_series
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  freezed_annotation: 
  json_annotation:
  dio: 

  flutter: 
    sdk: flutter

dev_dependencies: 

  flutter_lints: ^2.0.0
  freezed: 
  json_serializable: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.8

flutter: 
  uses-material-design: true

